# Generated by Django 4.2.11 on 2024-12-30 17:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_number', models.CharField(help_text='государственный регистрационный номер', max_length=10, unique=True, verbose_name='госномер')),
                ('brand', models.CharField(choices=[('NF', 'NEFAZ'), ('MS', 'MERCEDES'), ('IK', 'IKARUS'), ('MN', 'MEN')], help_text='марка автобуса', max_length=2, verbose_name='марка')),
                ('count_place', models.PositiveSmallIntegerField(help_text='количество посадочных мест', validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(120)], verbose_name='места')),
            ],
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='здесь указывается название города', max_length=30, unique=True, verbose_name='название города')),
            ],
            options={
                'verbose_name': 'город',
                'verbose_name_plural': 'города',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio_f', models.CharField(help_text='фамилия пассажира', max_length=100, verbose_name='фамилия')),
                ('fio_i', models.CharField(help_text='имя пассажира', max_length=100, verbose_name='имя')),
                ('fio_o', models.CharField(help_text='отчество пассажира', max_length=100, verbose_name='отчество')),
                ('passport', models.CharField(db_index=True, help_text='паспортные данные пассажира: 10 цифр', max_length=10, unique=True, verbose_name='паспорт')),
                ('money', models.DecimalField(decimal_places=2, help_text='сумма денег на счете', max_digits=8, verbose_name='деньги')),
            ],
            options={
                'verbose_name': 'пассажир',
                'verbose_name_plural': 'пассажиры',
                'ordering': ['fio_f', 'fio_i', 'fio_o'],
            },
        ),
        migrations.CreateModel(
            name='FinishCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_finish', models.ForeignKey(help_text='город назначения', on_delete=django.db.models.deletion.CASCADE, to='app.cities', verbose_name='финиш')),
            ],
            options={
                'verbose_name': 'город',
                'verbose_name_plural': 'города',
            },
        ),
        migrations.CreateModel(
            name='ListOfServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='наименование услуги', max_length=100, unique=True, verbose_name='услуга')),
                ('price', models.DecimalField(decimal_places=2, help_text='стоимость услуги', max_digits=8, verbose_name='цена')),
            ],
            options={
                'verbose_name': 'услуга',
                'verbose_name_plural': 'услуги',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id_route', models.IntegerField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, help_text='стоимость проезда по маршруту', max_digits=8, verbose_name='цена')),
                ('bus', models.ForeignKey(help_text='назначенный автобус', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.bus', verbose_name='автобус')),
                ('city_finish', models.ForeignKey(help_text='город назначения', on_delete=django.db.models.deletion.CASCADE, to='app.finishcity', verbose_name='куда')),
            ],
            options={
                'verbose_name': 'маршрут',
                'verbose_name_plural': 'маршруты',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.ManyToManyField(help_text='заказанные услуги', to='app.listofservices', verbose_name='услуги')),
            ],
            options={
                'verbose_name': 'допуслуга',
                'verbose_name_plural': 'допуслуги',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id_ticket', models.IntegerField(primary_key=True, serialize=False)),
                ('client', models.ForeignKey(help_text='пассажир', on_delete=django.db.models.deletion.CASCADE, to='app.client', verbose_name='пассажир')),
                ('route', models.ForeignKey(help_text='маршрут поездки', on_delete=django.db.models.deletion.CASCADE, to='app.route', verbose_name='маршрут')),
                ('services', models.OneToOneField(help_text='дополнительные услуги', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.services', verbose_name='услуги')),
            ],
            options={
                'verbose_name': 'билет',
                'verbose_name_plural': 'билеты',
            },
        ),
        migrations.CreateModel(
            name='StartCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_start', models.ForeignKey(help_text='город отправления', on_delete=django.db.models.deletion.CASCADE, to='app.cities', verbose_name='старт')),
            ],
            options={
                'verbose_name': 'город',
                'verbose_name_plural': 'города',
            },
        ),
        migrations.AddField(
            model_name='route',
            name='city_start',
            field=models.ForeignKey(help_text='город отправления', on_delete=django.db.models.deletion.CASCADE, to='app.startcity', verbose_name='откуда'),
        ),
        migrations.CreateModel(
            name='BusDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='фамилия водителя', max_length=70, unique=True, verbose_name='фамилия')),
                ('last_name', models.CharField(help_text='имя водителя', max_length=35, verbose_name='имя')),
                ('use_bus', models.OneToOneField(help_text='используемый автобус', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.bus', verbose_name='автобус')),
            ],
            options={
                'verbose_name': 'водитель',
                'verbose_name_plural': 'водители',
            },
        ),
    ]
