# Generated by Django 4.2.11 on 2024-12-30 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_bus_options_alter_finishcity_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='service',
            field=models.ManyToManyField(help_text='заказанные услуги', null=True, to='app.listofservices', verbose_name='услуги'),
        ),
    ]
