# Generated by Django 4.2.11 on 2024-12-31 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_services_service_remove_ticket_services_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listofservices',
            name='service',
            field=models.ForeignKey(blank=True, default=None, help_text='номер заказа', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.services', verbose_name='заказ'),
        ),
    ]
