# Generated by Django 4.2.11 on 2024-12-31 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_listofservices_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listofservices',
            name='service',
        ),
        migrations.AddField(
            model_name='listofservices',
            name='service',
            field=models.ManyToManyField(blank=True, default=None, help_text='номер заказа', null=True, to='app.services', verbose_name='заказ'),
        ),
    ]
