# Generated by Django 4.2.11 on 2024-12-31 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_listofservices_service_listofservices_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listofservices',
            name='service',
        ),
        migrations.AddField(
            model_name='listofservices',
            name='service',
            field=models.ForeignKey(blank=True, default=None, help_text='номер заказа', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.services', verbose_name='заказ'),
        ),
    ]
