# Generated by Django 4.2.11 on 2024-12-31 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_listofservices_service_listofservices_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listofservices',
            name='service',
        ),
        migrations.AddField(
            model_name='services',
            name='service',
            field=models.ManyToManyField(blank=True, default=None, help_text='тип дополнительный услуги', null=True, to='app.listofservices', verbose_name='тип'),
        ),
    ]
