# Generated by Django 4.2.11 on 2025-01-02 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0008_remove_listofservices_service_services_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='owner',
            field=models.ForeignKey(help_text='пользователь который регистрировал билет', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.AlterField(
            model_name='services',
            name='service',
            field=models.ManyToManyField(blank=True, default=None, help_text='тип дополнительный услуги', to='app.listofservices', verbose_name='тип'),
        ),
    ]
