# Generated by Django 4.2.11 on 2025-01-02 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_ticket_owner_alter_services_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='passport',
            field=models.CharField(db_index=True, help_text='паспортные данные пассажира: 10 цифр', max_length=10, verbose_name='паспорт'),
        ),
    ]
